version: '3'

services:
        backend:
                build:
                        context: ./backend
                command: gunicorn DRF_test.wsgi --bind 0.0.0.0:8000
                ports:
                        - "8000:8000"
        frontend:
                build:
                        context: ./frontend
                volumes:
                        - react_build:/react/.next/server/pages
                ports:
                        - "3000:3000"
        nginx:
                image: nginx:latest
                ports:
                        - 80:8080
                volumes:
                        - ./nginx/nginx_setup.conf:/etc/nginx/conf.d/default.conf:ro
                        - react_build:/var/www/react
                depends_on:
                        - backend
                        - frontend
volumes:
        react_build:
